FROM node:lts-slim

RUN apt-get update && apt-get install -y make wget curl
RUN npx playwright@1.51.1 install --with-deps --only-shell chromium
RUN npm install -g @angular/cli

ENV CHROME_BIN=/root/.cache/ms-playwright/chromium_headless_shell-1161/chrome-linux/headless_shell


