name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container: liz13/ww_public:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Set Chrome Binary Path
        run: echo "CHROME_BIN=/usr/bin/google-chrome-stable" >> $GITHUB_ENV

      - name: Run Unit Tests
        run: make unit-tests

  # deploy:
  #   name: Build & Push Docker Image
  #   runs-on: ubuntu-latest
  #   needs: tests
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Set Up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.REGISTRY_USER }}
  #         password: ${{ secrets.REGISTRY_PASS }}

  #     - name: Build Docker Image
  #       run: docker build -t liz13/wonderworld:${{ github.run_id }} -f Dockerfile.cd .

  #     - name: Push Docker Image
  #       run: docker push liz13/wonderworld:${{ github.run_id }}
